Implements two (failing) NLBVP tests in the ball. - test_heat_ball_nlbvp: fully implemented, including final assert check.  Failing on `solver.newton_iteration` with: `AttributeError: 'LiftTauBall' object has no attribute 'radial_basis'` - test_lane_embden: mostly implemented, but missing final assert check.  Failing on problem construction with: `TypeError: unsupported operand type(s) for @: 'BallBasis' and 'BallBasis'`